spring:
  application:
    name: eureka-server-service
  config:
    import: optional:configserver:http://localhost:8850

server:
  port: 8872

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
